LES_ROOT_PATH=$$PWD

INCLUDEPATH+=$$LES_ROOT_PATH/zmq/include

LES_LIB_PATH=$$LES_ROOT_PATH/zmq/lib
LES_LIB_NAME=libzmq-mt-gd-4_3_3

LIBS += -L$$LES_LIB_PATH -l$$LES_LIB_NAME

DESTDIR = $$LES_ROOT_PATH/bin
